//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cii.Lar.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cii.Lar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap assign {
            get {
                object obj = ResourceManager.GetObject("assign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string buttonSaveStr {
            get {
                return ResourceManager.GetString("buttonSaveStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        internal static string buttonSelectStr {
            get {
                return ResourceManager.GetString("buttonSelectStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Infomation 的本地化字符串。
        /// </summary>
        internal static string buttonSysInfoStr {
            get {
                return ResourceManager.GetString("buttonSysInfoStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap capture {
            get {
                object obj = ResourceManager.GetObject("capture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap elliptical {
            get {
                object obj = ResourceManager.GetObject("elliptical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap files {
            get {
                object obj = ResourceManager.GetObject("files", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        internal static string labelItem1Str {
            get {
                return ResourceManager.GetString("labelItem1Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string labelItemLanguageStr {
            get {
                return ResourceManager.GetString("labelItemLanguageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Storage Path 的本地化字符串。
        /// </summary>
        internal static string labelItemStoragePathStr {
            get {
                return ResourceManager.GetString("labelItemStoragePathStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap laser {
            get {
                object obj = ResourceManager.GetObject("laser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap line {
            get {
                object obj = ResourceManager.GetObject("line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap measure {
            get {
                object obj = ResourceManager.GetObject("measure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap polygon {
            get {
                object obj = ResourceManager.GetObject("polygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap print {
            get {
                object obj = ResourceManager.GetObject("print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap print_preview {
            get {
                object obj = ResourceManager.GetObject("print preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap rectangular {
            get {
                object obj = ResourceManager.GetObject("rectangular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ruler {
            get {
                object obj = ResourceManager.GetObject("ruler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Rulers_RulerOrigin {
            get {
                object obj = ResourceManager.GetObject("Rulers.RulerOrigin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Rulers_RulerOriginSnap {
            get {
                object obj = ResourceManager.GetObject("Rulers.RulerOriginSnap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap scale {
            get {
                object obj = ResourceManager.GetObject("scale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap screenshort {
            get {
                object obj = ResourceManager.GetObject("screenshort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap setting {
            get {
                object obj = ResourceManager.GetObject("setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        internal static string settingFormTitleStr {
            get {
                return ResourceManager.GetString("settingFormTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Report to create a Technical Support Request. 的本地化字符串。
        /// </summary>
        internal static string StrCreateReport {
            get {
                return ResourceManager.GetString("StrCreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string StrOK {
            get {
                return ResourceManager.GetString("StrOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program may run out of memory, please restart the program. 的本地化字符串。
        /// </summary>
        internal static string StrOutOfMemory {
            get {
                return ResourceManager.GetString("StrOutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report 的本地化字符串。
        /// </summary>
        internal static string StrReport {
            get {
                return ResourceManager.GetString("StrReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encountered an unknown error. Please restart the program. 的本地化字符串。
        /// </summary>
        internal static string StrUnknownErrorMsg {
            get {
                return ResourceManager.GetString("StrUnknownErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capture Screen 的本地化字符串。
        /// </summary>
        internal static string toolStripButtonCaptureStr {
            get {
                return ResourceManager.GetString("toolStripButtonCaptureStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elliptical 的本地化字符串。
        /// </summary>
        internal static string toolStripButtonEllipticalStr {
            get {
                return ResourceManager.GetString("toolStripButtonEllipticalStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laser 的本地化字符串。
        /// </summary>
        internal static string toolStripButtonLaserStr {
            get {
                return ResourceManager.GetString("toolStripButtonLaserStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line 的本地化字符串。
        /// </summary>
        internal static string toolStripButtonLineStr {
            get {
                return ResourceManager.GetString("toolStripButtonLineStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ploygon 的本地化字符串。
        /// </summary>
        internal static string toolStripButtonPolygonStr {
            get {
                return ResourceManager.GetString("toolStripButtonPolygonStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rectangle 的本地化字符串。
        /// </summary>
        internal static string toolStripButtonRectangleStr {
            get {
                return ResourceManager.GetString("toolStripButtonRectangleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale 的本地化字符串。
        /// </summary>
        internal static string toolStripButtonScaleStr {
            get {
                return ResourceManager.GetString("toolStripButtonScaleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        internal static string toolStripButtonSettingStr {
            get {
                return ResourceManager.GetString("toolStripButtonSettingStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capture Video 的本地化字符串。
        /// </summary>
        internal static string toolStripButtonVideoStr {
            get {
                return ResourceManager.GetString("toolStripButtonVideoStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom In 的本地化字符串。
        /// </summary>
        internal static string toolStripButtonZoomInStr {
            get {
                return ResourceManager.GetString("toolStripButtonZoomInStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom Out 的本地化字符串。
        /// </summary>
        internal static string toolStripButtonZoomOutStr {
            get {
                return ResourceManager.GetString("toolStripButtonZoomOutStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Archiving 的本地化字符串。
        /// </summary>
        internal static string toolStripFilesStr {
            get {
                return ResourceManager.GetString("toolStripFilesStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap um {
            get {
                object obj = ResourceManager.GetObject("um", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap video {
            get {
                object obj = ResourceManager.GetObject("video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap view {
            get {
                object obj = ResourceManager.GetObject("view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap zoom {
            get {
                object obj = ResourceManager.GetObject("zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Zoom_32 {
            get {
                object obj = ResourceManager.GetObject("Zoom-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Zoom_in {
            get {
                object obj = ResourceManager.GetObject("Zoom in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Zoom_out {
            get {
                object obj = ResourceManager.GetObject("Zoom out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap zoomFit {
            get {
                object obj = ResourceManager.GetObject("zoomFit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
