//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cii.Lar.Res {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LaserAlignment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LaserAlignment() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cii.Lar.Res.LaserAlignment", typeof(LaserAlignment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Align Laser 的本地化字符串。
        /// </summary>
        internal static string StrAlignLaser {
            get {
                return ResourceManager.GetString("StrAlignLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finish 的本地化字符串。
        /// </summary>
        internal static string StrFinish {
            get {
                return ResourceManager.GetString("StrFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string StrNext {
            get {
                return ResourceManager.GetString("StrNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove any embryos from the  field of view.
        ///Place an empty Petri dish or slide onto the microscope stage. 的本地化字符串。
        /// </summary>
        internal static string StrPreSet0 {
            get {
                return ResourceManager.GetString("StrPreSet0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The pilot is now switched on. Adjust the focus if necessary so that the Pilot laser spot appears as small as possible on the monitor.
        ///If the red spot appears too faint then reduce the intensity of the illumination or adjust the brightness of the pilot laser using the rear panel control.
        ///Click the pilot laser on screen. 的本地化字符串。
        /// </summary>
        internal static string StrPreSet1 {
            get {
                return ResourceManager.GetString("StrPreSet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string StrSave {
            get {
                return ResourceManager.GetString("StrSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calibration of the laser has now been complete.
        ///
        ///Click Finish to save the calibration. 的本地化字符串。
        /// </summary>
        internal static string StrStepComplete {
            get {
                return ResourceManager.GetString("StrStepComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The pilot laser has moved.
        ///
        ///Click the centre of the pilot laser on screen. 的本地化字符串。
        /// </summary>
        internal static string StrStepFive {
            get {
                return ResourceManager.GetString("StrStepFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The pilot laser has moved.
        ///
        ///Click the centre of the pilot laser on screen. 的本地化字符串。
        /// </summary>
        internal static string StrStepFour {
            get {
                return ResourceManager.GetString("StrStepFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The pilot laser is in position whitch should be visible on the screen.
        ///Check you can see the pilot laser on screen.
        ///Adjust the focus if necessary so that the Pilot laser spot appears as small as possible on the monitor.
        ///If the red spot appears too faint then reduce the intensity of the illumination or adjust the brightness of the pilot laser using the rear panel control.
        ///Click the pilot laser on screen. 的本地化字符串。
        /// </summary>
        internal static string StrStepOne {
            get {
                return ResourceManager.GetString("StrStepOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The pilot laser has moved.
        ///
        ///Click the centre of the pilot laser on screen. 的本地化字符串。
        /// </summary>
        internal static string StrStepSeven {
            get {
                return ResourceManager.GetString("StrStepSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The pilot laser has moved.
        ///
        ///Click the centre of the pilot laser on screen. 的本地化字符串。
        /// </summary>
        internal static string StrStepSix {
            get {
                return ResourceManager.GetString("StrStepSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The pilot laser has now moved by a small amount.
        ///
        ///Click the centre of the pilot laser on screen. 的本地化字符串。
        /// </summary>
        internal static string StrStepThree {
            get {
                return ResourceManager.GetString("StrStepThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laser Target Alignment - Step Complete 的本地化字符串。
        /// </summary>
        internal static string StrStepTitleComplete {
            get {
                return ResourceManager.GetString("StrStepTitleComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laser Target Alignment - Step Five 的本地化字符串。
        /// </summary>
        internal static string StrStepTitleFive {
            get {
                return ResourceManager.GetString("StrStepTitleFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laser Target Alignment - Step Four 的本地化字符串。
        /// </summary>
        internal static string StrStepTitleFour {
            get {
                return ResourceManager.GetString("StrStepTitleFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laser Target Alignment - Step One 的本地化字符串。
        /// </summary>
        internal static string StrStepTitleOne {
            get {
                return ResourceManager.GetString("StrStepTitleOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laser Target Alignment - Step Seven 的本地化字符串。
        /// </summary>
        internal static string StrStepTitleSeven {
            get {
                return ResourceManager.GetString("StrStepTitleSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laser Target Alignment - Step Six 的本地化字符串。
        /// </summary>
        internal static string StrStepTitleSix {
            get {
                return ResourceManager.GetString("StrStepTitleSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laser Target Alignment - Step Three 的本地化字符串。
        /// </summary>
        internal static string StrStepTitleThree {
            get {
                return ResourceManager.GetString("StrStepTitleThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laser Target Alignment - Step Two 的本地化字符串。
        /// </summary>
        internal static string StrStepTitleTwo {
            get {
                return ResourceManager.GetString("StrStepTitleTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The pilot laser has now moved by a small amount.
        ///
        ///Click the centre of the pilot laser on screen. 的本地化字符串。
        /// </summary>
        internal static string StrStepTwo {
            get {
                return ResourceManager.GetString("StrStepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laser Target Alignment 的本地化字符串。
        /// </summary>
        internal static string StrTitle {
            get {
                return ResourceManager.GetString("StrTitle", resourceCulture);
            }
        }
    }
}
